
name: 08-03-Contexts - Inputs

on:
  workflow_dispatch:
    inputs:
      Jiracard:
        type: string
      ReleaseVersion:
        type: string
      Current_version:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Workflow Input
        run: |
          echo "DEBU ${{ inputs.Jiracard }}"
           echo "ReleaseVersion ${{ inputs.ReleaseVersion }}"
           echo "Current_version ${{ inputs.Current_version }}"


