
name: 08-03-Contexts - Inputs

on:
  workflow_dispatch:
    inputs:
      Jiracard:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Workflow Input
        run: |
          echo "DEBU ${{ inputs.Jiracard }}"
