
name: 08-03-Contexts - Inputs

on:
  workflow_dispatch:
    inputs:
      Jiracard:
        type: string
      ReleaseVersion:
        type: string
      Current_version:
        type: string
      upload:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Workflow Input
        run: |
          echo "DEBU ${{ inputs.Jiracard }}"
           echo "ReleaseVersion ${{ inputs.ReleaseVersion }}"
        
            if [[ ${{ inputs.upload }} == true]]; then
                    
                    echo "version tag is $${{ inputs.upload }}"
            else
                    echo "There is no github tag reference, skipping"
            fi
