name : context_varaibles
on:
   workflow_dispatch:    
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Use Workflow variable from git
          run: |
            echo "print  ${{ var.config }}"
          